_core:
  default_config_hash: LqXuXXQCTd1NWw7dGLef0PCi3_aEEWQuogAblo4hHaE
hotlink: false
origin: 'https://caminofrances:Swolenk4@caminofrances-stg.metadrop.pro'
origin_dir: sites/default/files
proxy_headers: ''
use_imagecache_root: true
verify: true
excluded_extensions: ''
